### ISSUE TITLE
Merge 2.1 into master

### ISSUE THREAD

**Issue by chadmoone** [JChristensen/Timer#16]
I was trying to figure out why 2.1 was not in the master, and I found this wiki entry: https://github.com/JChristensen/Timer/wiki

Do you plan to leave the master at 1.x indefinitely, since there is a book referencing the library?  I don't know which book it is, but they really should have referenced a specific version of it.  Of course, it's too late now...

The features and documentation are _much_ nicer in 2.1, and I think it's a real shame to hide that from most people who come across the library because of an unfortunately ambiguous book reference.

Would it be possible to just add a special note at the top of the `README.md` for readers of the book?

Let me know if there's anything I can do to help.

**Comment by JChristensen** [comment]
This is really Simon Monk's library, and it's referenced by one of his books. I'm not sure anyone anticipated the level of interest in developing this library (but that's a good thing). So for better or worse, the two-branch structure needs to be maintained.

Adding a note to the README file is a very good suggestion.

**Comment by q2dg** [comment]
+1 for @chadmoone thought

**Comment by per1234** [comment]
The way to deal with versions is through git tags, not branches. People can grab any version they like through the [releases ](https://github.com/JChristensen/Timer/releases)page of this repository.

It would make some sense have two branches:
- 1.x.x: Ongoing development, while maintaining 1.x.x API compatibility. It seems this is what is happening in the current master branch.
- master: Ongoing development, which may break 1.x.x API compatibility. It seems this is what is happening in the current v2.1 branch.

The readme should clearly document the purpose of each branch so people know which they want to use and where to submit PRs.

If you want people coming from the book's link to land in the 1.x.x branch you can set that as the repository's default branch (https://github.com/JChristensen/Timer/settings/branches).

**Comment by JChristensen** [comment]
That may well be, but I don't have the bandwidth required.
