### ISSUE TITLE
Unexpected results passing struct to callback

### ISSUE THREAD

**Issue by brunnels** [JChristensen/Timer#21]
```c++
#include "Timer.h"
Timer t;

struct PinData {
  uint8_t pin;
  uint8_t state;
};

void checkStruct(void *context)
{
  PinData* pinStruct = (PinData*)context;
  Serial.print("pinStruct->pin should be 13, it's actually ");
  Serial.println(pinStruct->pin);
}

void setup()
{
  Serial.begin(115200);

  PinData pinStruct = { 13, HIGH };
  Serial.print("pinStruct.pin = ");
  Serial.println(pinStruct.pin);

  t.every(1000, checkStruct, (void*) &pinStruct); 
}

void loop()
{
  t.update();
}
```

**Comment by SandyWalsh** [comment]
Your PinData data structure is a local variable (created on the call stack) ... it vanishes when setup() exists. Create PinData as a global variable and it should be fine.

**Comment by brunnels** [comment]
Okay, that works.  Thanks for clearing up my mistake.

```c++
#include "Timer.h"
Timer t;

struct PinData {
  uint8_t pin;
  uint8_t state;
};

PinData pinStruct;

void checkStruct(void *context)
{
  PinData* test = (PinData*)context;
  Serial.print("test->pin should be 13, it's actually ");
  Serial.println(test->pin);
}

void setup()
{
  Serial.begin(115200);

  pinStruct = { 13, HIGH };
  Serial.print("pinStruct.pin = ");
  Serial.println(pinStruct.pin);

  t.every(1000, checkStruct, (void*) &pinStruct);
}

void loop()
{
  t.update();
}
```

**Comment by brunnels** [comment]
I need to pass pin number and state to a callback from a struct packet coming in from RF24Network.  I can't use oscillate because I need to send a status packet after changing the pin.  The most efficient way to do this was to add a few more methods to Timer so I could pass pin, pinState, and void* context to the callback.  This made sense to me because the Event object already had defined pin and pinState so better to use that than create additional globals to store the info.
