### ISSUE TITLE
Does timer works correct after 50 days uptime? 

### ISSUE THREAD

**Issue by palivoda** [JChristensen/Timer#40]
See:  https://www.arduino.cc/reference/en/language/functions/time/millis/

 This number will overflow (go back to zero), after approximately 50 days.

> if (now - lastEventTime >= period)

Events will stuck after NOW reset to 0 and lastEventTime still at max value.

**Comment by JChristensen** [comment]
It works fine after 50 days. The only limitation is that `period` cannot be longer than ~49.7 days.

**Comment by JChristensen** [comment]
Also see #22.
